Create schema
NoelLincoln/database_from_diagram pull request #1
Opened 2023-11-15 18:42 UTC by NoelLincoln

Hello 👋,

In this milestone we were able to create a schema from a sample entity relation diagram.

The diagram is in the root folder structure and the sql statements we used are in the schema_based_on_diagram.sql file

Below are the tables for each table plus the join table for the many to many relationship between medical_history and treatments:

- Patients table:
![patients](https://github.com/NoelLincoln/database_from_diagram/assets/23360657/11d639ae-d202-457e-9d15-232c83330f2a)

- Medical histories table:
![medical_histories](https://github.com/NoelLincoln/database_from_diagram/assets/23360657/bbe40dde-905a-4735-9ce3-461eba1883e9)

- Treatments table:
![treatments](https://github.com/NoelLincoln/database_from_diagram/assets/23360657/3ec7f42c-f897-477f-9707-f2c16adc3284)

- Invoices table:
![invoices](https://github.com/NoelLincoln/database_from_diagram/assets/23360657/0a386d6d-2066-48dd-a8fe-734c35196de4)

- Invoices items table:
![invoices_items](https://github.com/NoelLincoln/database_from_diagram/assets/23360657/db1bd5ed-2953-4332-9362-4e90eaa5ff33)

- Medical_treatments table which handles the many to many relationship between medical histories and treatments
- 
![medical_treatment_foreign_keys](https://github.com/NoelLincoln/database_from_diagram/assets/23360657/82de73da-baa9-47fd-a0c6-c92adb2e469b)

2023-11-15 19:29 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @NoelLincoln, @FilbertKimasa, @ometman , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- Tables have primary and foreign keys :+1: 
- Tables created based on the given diagram :+1: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-15 19:29 UTC, FrederickMih commented on schema_based_on_diagram.sql
> +type TIMESTAMP,
- [ ] Hi team, the data type of the column `type`, according to the diagram should be `varchar`. It would be nice to adhere to our projects requirement.

2023-11-15 19:29 UTC, FrederickMih commented on schema_based_on_diagram.sql
> +);
- [ ] As requested in the requirements, let's kindly make sure that all foreign keys have indexes created :+1: Indexes help you quickly browse the database and figured out the data you need

2023-11-16 07:10 UTC, ometman commented on schema_based_on_diagram.sql
> +type TIMESTAMP,
Thanks for the reminder. Fixed.

2023-11-16 07:46 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @NoelLincoln, @ometman and @FilbertKimasa,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-16 07:46 UTC, TedLivist commented on schema_based_on_diagram.sql
> +CREATE INDEX idx_med_treat_id ON treatments(id);
- [ ] The table `treatments` has no foreign so kindly remove this index on it.

- [ ] The indexes should be created on the foreign keys of the tables, not the primary keys. The `medical_histories` should have index for the `patient_id`. See an example

  ```
  CREATE INDEX ON medical_histories (patient_id);
  ```

2023-11-16 07:46 UTC, TedLivist commented on schema_based_on_diagram.sql
> +medical_history_id INT UNIQUE REFERENCES medical_histories(id)
- [ ] Kindly add the missing index for this `medical_history_id` foreign key in the `invoices` table

2023-11-16 07:46 UTC, TedLivist commented on schema_based_on_diagram.sql
> + treatment_id INT REFERENCES treatments(id)
- [ ] Kindly add the missing indexes for these `invoice_id` and `treatment_id` foreign keys in the `invoice_items` table.

2023-11-16 07:46 UTC, TedLivist commented on schema_based_on_diagram.sql
> +    medical_treatment_id INT REFERENCES treatments(id),
- [ ] Kindly add the missing index for these `medical_history_id` and `medical_treatment_id` foreign keys in the `medical_treatment` table.

  In conclusion you should have a total of 6 indexes for the 6 foreign keys, not just one as you tried defining earlier.

2023-11-16 08:23 UTC, ometman commented on schema_based_on_diagram.sql
> +CREATE INDEX idx_med_treat_id ON treatments(id);
That was a wrong push. 😄

2023-11-16 08:23 UTC, ometman commented on schema_based_on_diagram.sql
> +medical_history_id INT UNIQUE REFERENCES medical_histories(id)
That was a wrong push. 😄

2023-11-16 08:23 UTC, ometman commented on schema_based_on_diagram.sql
> +    medical_treatment_id INT REFERENCES treatments(id),
That was a wrong push. 😄

2023-11-16 08:26 UTC, ometman commented
The right changes made and committed, now pushed. Thanks you.

2023-11-16 10:11 UTC, danmainah approved these changes
Hi @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️  Implemented the changes requested to ensure all foreign keys have indexes.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-17 07:54 UTC, merged